name: pull-request-validation
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: Branch name
        required: true
        type: string
      test_category:
        description: The test category to run
        required: false
        type: string
        default: sanity
env:
  VALIDATION_USER_NAME: ogd_test_user
  ORACLE_DRIVER_MODULE: "github.com/oracle/go-oracledb/v26/oracle"
  COVERAGE_THRESHOLD: 80

concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: true

jobs:
  check_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 10
      - uses: ./.github/actions/setup-go-env
      - run: "gofmt -l $(find ${{ github.workspace }} -type f \\( -not -path '*/.go/*' -a -not -path */.git/* \\) -name \\*.go) | awk ' {print $0} END {exit NR}'"

  check_source:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 10
      - uses: ./.github/actions/setup-go-env
      - run: go vet ./...

  build:
    needs:
      - check_source
      - check_format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/setup-go-env
      - run: go build ./...

  unit_tests:
    needs:
      - build
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/setup-go-env
      - uses: ./.github/actions/list-go-packages
        id: go-packages
      - run: |
          mkdir -p ${{ github.workspace }}/coverage/unit
      - run: |
          go test -race -parallel=10 -shuffle=on -v ${{ steps.go-packages.outputs.packages }} -coverpkg=./... -cover -run TestCategoryExecutor -args -test.gocoverdir=${{ github.workspace }}/coverage/unit  -test.category="unitary"
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: coverage-unit
          path: ${{ github.workspace }}/coverage/unit
          if-no-files-found: error


  validate_driver_tp:
    if: ${{ github.repository == 'oracle/go-oracledb' }}
    runs-on: [ self-hosted, Linux, X64, OracleTestPilot ]
    strategy:
      matrix:
        include:
          - rdbms: base-database-service-26ai
    needs:
      - unit_tests
    timeout-minutes: 10
    env:
      ORACLE_GO_LOGGING_DESTINATION: STDOUT
      ORACLE_GO_LOGGING_LEVEL: DEBUG
      TEST_CATEGORY: ${{ case(github.event.inputs.test_category == '', 'sanity', github.event.inputs.test_category) }}
      #ORACLE_GO_LOGGING_INCLUDESENSITIVE: "true"
      #ORACLE_GO_DRIVER_DEBUG_PACKETS: "true"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/setup-go-env
      - uses: ./.github/actions/list-go-packages
        id: go-packages
      - name: Create test database
        id: create_database
        uses: oracle-actions/setup-testpilot@ad55a0d7294112c44a9cc9a38f4b3d293da8fcf0 # 1.0.31
        with:
          oci-service: ${{ matrix.rdbms }}
          action: create
          user: ${{ env.VALIDATION_USER_NAME }}
          fully-qualified-names: true
      - uses: ./.github/actions/setup-test-configuration
        with:
          database-version: ${{ steps.create_database.outputs.database_version }}
          database-service: ${{ steps.create_database.outputs.database_service }}
          database-host: ${{ steps.create_database.outputs.database_host }}
          database-port: ${{ steps.create_database.outputs.database_port }}
          database-protocol: ${{ steps.create_database.outputs.database_protocol }}
          database-user: ${{ steps.create_database.outputs.database_user }}
          database-password: ${{ steps.create_database.outputs.database_password }}
      - run: |
          mkdir -p ${{ github.workspace }}/coverage/sanity
      - run: |
          go test -race -parallel=10  -shuffle=on -v ${{ steps.go-packages.outputs.packages }} -coverpkg=./... -cover -run TestCategoryExecutor  -args -test.gocoverdir=${{ github.workspace }}/coverage/sanity -driver.config.filename=${{ github.workspace }}/go-driver-config.json -driver.config.name=pipeline_test  -test.category="${{ env.TEST_CATEGORY }}"
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: coverage-sanity
          path: ${{ github.workspace }}/coverage/sanity
          if-no-files-found: error
      - uses: oracle-actions/setup-testpilot@0e9d9b877bb35f65e3f1f1c54c6a425329dd7ece # v1.0.27
        if: always()
        with:
          oci-service: ${{ matrix.rdbms }}
          action: delete
          user: ${{ env.VALIDATION_USER_NAME }}
  coverage:
    needs:
      - unit_tests
      - validate_driver_tp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/setup-go-env
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: coverage-unit
          path: ${{ github.workspace }}/coverage/unit
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: coverage-sanity
          path: ${{ github.workspace }}/coverage/sanity
      - run: |
          mkdir -p ${{ github.workspace }}/coverage/merged
          go tool covdata merge -i=${{ github.workspace }}/coverage/unit,${{ github.workspace }}/coverage/sanity -o ${{ github.workspace }}/coverage/merged
          go tool covdata textfmt -i=${{ github.workspace }}/coverage/merged -o=${{ github.workspace }}/coverage.out
      - run: |
          go tool cover -func=${{ github.workspace }}/coverage.out |awk -v threshold=${{ env.COVERAGE_THRESHOLD }} '{split($1,t,":") ; sub(/%$/,"",$3) ; files[t[1]]+=$3 ; files_a[t[1]]++} END {for (k in files) { if (k != "total") printf ("%80s --> %.2f%%\n",k,files[k]/files_a[k]);} } END {printf ("%80s --> %.2f%%\n","total",files["total"]) ; if (files["total"] < threshold) {exit 1}} '
